theme: jekyll-theme-slate
title: Edgar Alejandro Cantú Costilla
description: Chemical engineer who aims to present excellent results in the projects assigned, with great interest in the automation of tasks through programming and committed to continue learning.
